/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#8eff71",
        "background": "#0d0d16",
        "error": "#ff7351",
        "on-secondary": "#455900",
        "tertiary-container": "#00eefc",
        "on-primary-fixed": "#064200",
        "on-primary-container": "#0b5800",
        "tertiary-fixed": "#00eefc",
        "primary-container": "#2ff801",
        "on-surface": "#f2effb",
        "secondary-container": "#506600",
        "surface-dim": "#0d0d16",
        "secondary-fixed": "#c3f400",
        "on-error-container": "#ffd2c8",
        "inverse-primary": "#106f00",
        "on-tertiary-fixed-variant": "#005e64",
        "outline": "#76747f",
        "surface-bright": "#2b2b38",
        "outline-variant": "#484751",
        "secondary-dim": "#b7e500",
        "primary-fixed": "#2ff801",
        "surface-container-high": "#1f1f2a",
        "surface-variant": "#252531",
        "surface-tint": "#8eff71",
        "on-secondary-fixed": "#354500",
        "tertiary-dim": "#00deec",
        "primary-dim": "#2be800",
        "on-secondary-fixed-variant": "#4e6300",
        "secondary": "#c3f400",
        "primary-fixed-dim": "#2be800",
        "on-primary": "#0d6100",
        "error-container": "#b92902",
        "surface": "#0d0d16",
        "surface-container-highest": "#252531",
        "on-error": "#450900",
        "on-tertiary-container": "#005359",
        "surface-container": "#191923",
        "on-tertiary": "#005d63",
        "tertiary": "#8ff5ff",
        "error-dim": "#d53d18",
        "inverse-surface": "#fcf8ff",
        "surface-container-low": "#13131c",
        "on-background": "#f2effb",
        "on-primary-fixed-variant": "#0d6200",
        "tertiary-fixed-dim": "#00deec",
        "on-secondary-container": "#efffbc",
        "on-tertiary-fixed": "#003f43",
        "inverse-on-surface": "#55545e",
        "secondary-fixed-dim": "#b7e500",
        "on-surface-variant": "#acaab5",
        "surface-container-lowest": "#000000"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Space Grotesk"]
      },
      borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
    },
  },
  plugins: [],
};
